version: "3"


services:
  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    expose:
      - "1025"
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - shlokas

  shlokas:
    image: shlokas-app
    depends_on:
      - db
      - auth
      - content
      - balancer
    ports:
      - "8080:80"
    networks:
      - shlokas
