version: "3"
name: 'shlokas'


services:
  db:
    image: ghcr.io/akdasa-studios/shlokas-db:latest
    restart: always
    expose:
      - 5984
    env_file:
      - ../environment.env
      - ../environment.local.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
    volumes:
      - ../_data/db:/opt/couchdb/data
    networks:
      - shlokas

  auth:
    image: ghcr.io/akdasa-studios/shlokas-auth:latest
    restart: always
    expose:
      - 3000
    env_file:
      - ../environment.env
      - ../environment.local.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shlokas
    volumes:
      - ../_data/auth:/app/shlokas-auth/.data
    healthcheck:
      test: ["CMD", "sh", "/app/shlokas-auth/.container/healthcheck.sh"]

  landing:
    image: ghcr.io/akdasa-studios/shlokas-landing:latest
    restart: always
    expose:
      - 80
    networks:
      - shlokas

  content:
    image: ghcr.io/akdasa-studios/shlokas-content:latest
    restart: always
    expose:
      - 80
    volumes:
      - ../_data/content:/app/content
    networks:
      - shlokas

  admin:
    image: ghcr.io/akdasa-studios/shlokas-admin:latest
    restart: always
    expose:
      - 80
    env_file:
      - ../environment.env
      - ../environment.local.env
    networks:
      - shlokas

  totp:
    image: ghcr.io/akdasa-studios/shlokas-totp:latest
    restart: always
    expose:
      - 8080
    env_file:
      - ../environment.env
      - ../environment.local.env
    networks:
      - shlokas

  balancer:
    image: ghcr.io/akdasa-studios/shlokas-balancer:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - ../environment.env
      - ../environment.local.env
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
      landing:
        condition: service_started
      admin:
        condition: service_started
      totp:
        condition: service_started
      content:
        condition: service_started
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - shlokas
    healthcheck:
      test: ["CMD", "sh", "/app/shlokas-balancer/.container/healthcheck.sh"]


networks:
  shlokas:
    name: shlokas
