version: "3"
services:
  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    expose:
      - "1025"
    ports:
      - "1080:1080"
      - "1025:1025"

  shlokas:
    image: shlokas:latest
    expose:
      - 80

  auth:
    environment:
      - EMAIL_HOST_LINK=http://balancer

