version: "3"
services:
  db:
    image: shlokas-database

  auth:
    image: shlokas-auth

  landing:
    image: shlokas-landing

  content:
    image: shlokas-content

  admin:
    image: shlokas-admin

  totp:
    image: shlokas-totp

  balancer:
    image: shlokas-balancer

  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    expose:
      - "1025"
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - shlokas
