version: "3"


services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config.json:/config.json
    command: --interval 300 --cleanup --include-stopped
