version: "3"
services:
  db:
    image: ghcr.io/akdasa-studios/shlokas-db:latest
    restart: always
    expose:
      - 5984
    env_file:
      - environment.env
      - environment.local.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/opt/couchdb/data

  db-bootstrap:
    image: ghcr.io/akdasa-studios/shlokas-db-bootstrap:latest
    env_file:
      - environment.env
      - environment.local.env
    depends_on:
      db:
        condition: service_healthy

  auth:
    image: ghcr.io/akdasa-studios/shlokas-auth:latest
    restart: always
    expose:
      - 3000
    env_file:
      - environment.env
      - environment.local.env
    depends_on:
      db:
        condition: service_healthy

  landing:
    image: ghcr.io/akdasa-studios/shlokas-landing:latest
    restart: always
    expose:
      - 80

  content:
    image: ghcr.io/akdasa-studios/shlokas-content:latest
    restart: always
    expose:
      - 80
    volumes:
      - ./content:/app/content

  admin:
    image: ghcr.io/akdasa-studios/shlokas-admin:latest
    restart: always
    expose:
      - 80
    env_file:
      - environment.env
      - environment.local.env

  totp:
    image: ghcr.io/akdasa-studios/shlokas-totp:latest
    restart: always
    expose:
      - 8080
    env_file:
      - environment.env
      - environment.local.env

  balancer:
    image: ghcr.io/akdasa-studios/shlokas-balancer:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - environment.env
      - environment.local.env
    depends_on:
      - db
      - auth
      - landing
      - admin
      - totp
      - content
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    command: --interval 300 --cleanup --include-stopped